# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 13:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_auto_20160817_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='memorandum',
            field=models.BooleanField(default=False, verbose_name='Memorandum signed'),
        ),
        migrations.AddField(
            model_name='institution',
            name='year',
            field=models.PositiveIntegerField(default=2016, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Year'),
        ),
    ]
