# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_institution_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='countries.Country'),
        ),
    ]
