# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 13:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_auto_20161005_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='year',
            field=models.PositiveIntegerField(default=2016, validators=[django.core.validators.MaxValueValidator(4000)], verbose_name='Year'),
        ),
    ]
