# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 13:56
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_auto_20161005_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
