# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_auto_20161005_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name'], 'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
    ]
