# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 20:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_auto_20161121_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='year',
            field=models.PositiveIntegerField(default=2017, validators=[django.core.validators.MaxValueValidator(4000)], verbose_name='Year'),
        ),
    ]
