# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_auto_20161024_1738'),
        ('institutions', '0012_auto_20170407_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='abbreviation',
            field=models.CharField(max_length=255, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together=set([('name', 'abbreviation', 'country')]),
        ),
    ]
