# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 12:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import wocat.cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0013_auto_20170810_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='year',
            field=models.PositiveIntegerField(default=wocat.cms.models.get_default_year_now, validators=[django.core.validators.MaxValueValidator(4000)], verbose_name='Year'),
        ),
    ]
