# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='author',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Author'),
            preserve_default=False,
        ),
    ]
