# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('medialibrary', '0002_auto_20160711_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='teaser_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
