# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0003_media_teaser_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtaildocs.Document'),
            preserve_default=False,
        ),
    ]
