# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0005_auto_20160803_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='medialibrary.MediaType', verbose_name='Type'),
            preserve_default=False,
        ),
    ]
