# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0011_auto_20161012_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ForeignKey(blank=True, help_text='This field is only used if the content is empty.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
