# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_continent'),
        ('medialibrary', '0012_auto_20161012_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Continent'),
        ),
    ]
