# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0015_fill_filter_spec_field'),
        ('medialibrary', '0014_medialibrarypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatype',
            name='default_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Default image'),
        ),
        migrations.AddField(
            model_name='mediatype',
            name='icon',
            field=models.CharField(blank=True, help_text='Fontawesome icon name.', max_length=255, verbose_name='Icon name'),
        ),
    ]
