# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0015_auto_20161024_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='country',
        ),
    ]
