# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_auto_20161205_1721'),
        ('medialibrary', '0020_auto_20161205_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='language',
            field=models.ManyToManyField(to='languages.Language'),
        ),
    ]
