# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 17:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0021_media_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2016, null=True, validators=[django.core.validators.MaxValueValidator(4000)], verbose_name='Year'),
        ),
    ]
