# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0031_auto_20170509_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediatype',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='mediatype',
            name='order',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
