# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('medialibrary', '0036_auto_20171207_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialibrarypage',
            name='es_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='medialibrarypage',
            name='fr_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
