# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 07:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wocat.cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('medialibrary', '0036_auto_20171207_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialibrarypage',
            name='es_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='medialibrarypage',
            name='fr_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='media',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=wocat.cms.models.get_default_year_now, null=True, validators=[django.core.validators.MaxValueValidator(4000)], verbose_name='Year'),
        ),
    ]
