# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 12:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import wocat.cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0037_auto_20171214_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=wocat.cms.models.get_default_year_now, null=True, validators=[django.core.validators.MaxValueValidator(4000)], verbose_name='Year'),
        ),
    ]
