# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 16:49
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('description', models.TextField(verbose_name='Description')),
                ('acronym', models.BooleanField(default=False, verbose_name='Is an acronym')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Glossar Entries',
                'verbose_name': 'Glossar Entry',
            },
        ),
    ]
