# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Coutries'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='country',
        ),
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='', max_length=3, primary_key=True, serialize=False, verbose_name='code (alpha3)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='name'),
            preserve_default=False,
        ),
    ]
