# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 14:05
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
