# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160713_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
