# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_initial_data'),
        ('news', '0007_auto_20160920_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='countries.Country'),
        ),
    ]
