# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_country_slug'),
        ('news', '0008_newspage_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='country',
        ),
        migrations.AddField(
            model_name='newspage',
            name='country',
            field=models.ManyToManyField(to='countries.Country'),
        ),
    ]
