# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields
import wocat.cms.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20161010_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsindexpage',
            name='header_images',
            field=wagtail.wagtailcore.fields.StreamField((('image', wocat.cms.blocks.ImageBlock()),), blank=True),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='lead',
            field=models.TextField(blank=True, verbose_name='Lead text'),
        ),
    ]
