# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20161012_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='countries',
        ),
    ]
