# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 15:57
from __future__ import unicode_literals

from django.db import IntegrityError
from django.db import migrations
from django.db import transaction


def load_initial_languages(apps, schema_editor):
    Language = apps.get_model('languages', 'Language')
    from django_languages.languages import LANGUAGES
    for code, name in LANGUAGES:
        if len(code) <= 3:
            try:
                # Duplicates should be prevented.
                with transaction.atomic():
                    Language.objects.create(
                        code=code,
                        name=name,
                    )
            except IntegrityError:
                pass


def unload_initial_languages(apps, schema_editor):
    Language = apps.get_model('languages', 'Language')
    for language in Language.objects.all():
        language.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_languages, unload_initial_languages),
    ]
