# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_initial_data_20161205_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='language code'),
        ),
    ]
