# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Newsletter subscription'),
        ),
    ]
