# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160620_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.CharField(blank=True, max_length=255, verbose_name='Expertise'),
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Organisation'),
        ),
    ]
