# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20160704_1534'),
        ('users', '0006_auto_20160627_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.Institution'),
        ),
    ]
