# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Experience')),
            ],
        ),
        migrations.CreateModel(
            name='UserKeyWorkTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Key work topics')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organisation',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address Information'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='fax',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='user',
            name='fax_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fax 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='function',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SLM specialists field level'), (2, 'SLM specialists (sub-)national level'), (3, 'SLM specialists regional and global levels')], null=True, verbose_name='Your function'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Mr'), ('f', 'Mrs')], max_length=1, verbose_name='Salutation'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', max_length=2, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=True, verbose_name='Newsletter subscription'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phone 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='user',
            name='second_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Second email'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='user',
            name='experiences',
            field=models.ManyToManyField(to='users.UserExperience'),
        ),
        migrations.AddField(
            model_name='user',
            name='key_work_topics',
            field=models.ManyToManyField(to='users.UserKeyWorkTopic'),
        ),
    ]
