# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160802_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experiences',
            field=models.ManyToManyField(blank=True, to='users.UserExperience'),
        ),
        migrations.AlterField(
            model_name='user',
            name='key_work_topics',
            field=models.ManyToManyField(blank=True, to='users.UserKeyWorkTopic'),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='userkeyworktopic',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Key work topics'),
        ),
    ]
