# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_auto_20161024_1738'),
        ('users', '0011_auto_20161108_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='countries.Country'),
        ),
    ]
