# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_country_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='country_new',
            new_name='country',
        ),
    ]
