# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_country_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='depricated',
            field=models.TextField(blank=True, verbose_name='Depricated data'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_and_conditions',
            field=models.BooleanField(default=False, verbose_name='Accepted terms and conditions'),
        ),
    ]
