# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20161115_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='depricated',
        ),
        migrations.AddField(
            model_name='user',
            name='deprecated',
            field=models.TextField(blank=True, verbose_name='Deprecated data'),
        ),
    ]
