# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-07 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20161115_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
