# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 10:17
from __future__ import unicode_literals

from django.db import migrations


def add_newsletter_permission(apps, schema_editor):
    User = apps.get_model('users', 'User')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')

    content_type = ContentType.objects.get_for_model(User)
    Permission.objects.create(
        codename='can_update_mailchimp',
        name='Can update MailChimp users',
        content_type=content_type,
    )


def remove_newsletter_permission(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Permission.objects.get(
        codename='can_update_mailchimp',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20170424_1213'),
    ]

    operations = [
        migrations.RunPython(
            code=add_newsletter_permission,
            reverse_code=remove_newsletter_permission
        ),
    ]
