# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20180201_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerlink',
            name='name',
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='target',
            field=models.ForeignKey(help_text='Always link the original page (in English)!', on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Page'),
        ),
    ]
