# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wocat.cms.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20160627_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpage',
            options={'verbose_name': 'Countries'},
        ),
        migrations.AddField(
            model_name='countrypage',
            name='header',
            field=wagtail.wagtailcore.fields.StreamField((('carousel', wagtail.wagtailcore.blocks.StructBlock((('images', wagtail.wagtailcore.blocks.ListBlock(wocat.cms.blocks.ImageBlock())), ('heading', wagtail.wagtailcore.blocks.CharBlock()), ('content', wocat.cms.blocks.RichTextBlock(required=False))))),), blank=True),
        ),
        migrations.AlterField(
            model_name='countrypage',
            name='contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
