# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 13:18
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
import wocat.cms.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20160627_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrypage',
            name='header',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='header',
        ),
        migrations.AddField(
            model_name='countrypage',
            name='header_images',
            field=wagtail.wagtailcore.fields.StreamField((('image', wocat.cms.blocks.ImageBlock()),), blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_images',
            field=wagtail.wagtailcore.fields.StreamField((('image', wocat.cms.blocks.ImageBlock()),), blank=True),
        ),
    ]
