# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields
import wocat.cms.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20160628_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='header_images',
            field=wagtail.wagtailcore.fields.StreamField((('image', wocat.cms.blocks.ImageBlock()),), blank=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='lead',
            field=models.TextField(blank=True, verbose_name='Lead text'),
        ),
        migrations.AddField(
            model_name='countrypage',
            name='header_images',
            field=wagtail.wagtailcore.fields.StreamField((('image', wocat.cms.blocks.ImageBlock()),), blank=True),
        ),
        migrations.AddField(
            model_name='countrypage',
            name='lead',
            field=models.TextField(blank=True, verbose_name='Lead text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_images',
            field=wagtail.wagtailcore.fields.StreamField((('image', wocat.cms.blocks.ImageBlock()),), blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='lead',
            field=models.TextField(blank=True, verbose_name='Lead text'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='header_images',
            field=wagtail.wagtailcore.fields.StreamField((('image', wocat.cms.blocks.ImageBlock()),), blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='lead',
            field=models.TextField(blank=True, verbose_name='Lead text'),
        ),
    ]
