# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_regionpage_regionspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionpage',
            name='countries',
            field=models.ManyToManyField(to='cms.CountryPage'),
        ),
    ]
