# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_projectcountriespage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcountriespage',
            options={'verbose_name': 'Project Countries'},
        ),
    ]
