# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_auto_20160921_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrypage',
            name='country',
        ),
    ]
