# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_initial_data'),
        ('cms', '0031_remove_countrypage_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrypage',
            name='country',
            field=models.ForeignKey(default='AUT', on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
            preserve_default=False,
        ),
    ]
