# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_countrypage_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrypage',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country', unique=True),
        ),
    ]
