# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_auto_20160928_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrypage',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='countries.Country'),
        ),
    ]
