# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0039_institutionspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='contact_person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_contact', to=settings.AUTH_USER_MODEL, verbose_name='Contact person'),
        ),
        migrations.AlterField(
            model_name='countrypage',
            name='contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_contact', to=settings.AUTH_USER_MODEL, verbose_name='Contact person'),
        ),
    ]
