# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0040_auto_20161114_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionpage',
            name='contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_contact', to=settings.AUTH_USER_MODEL, verbose_name='Contact person'),
        ),
    ]
