# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0045_auto_20161121_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(help_text='Fontawesome icon name', max_length=255)),
                ('url', models.URLField(help_text='Your social media page URL')),
                ('navigation', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='cms.TopNavigationSettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='topnavigationlink',
            old_name='footer',
            new_name='navigation',
        ),
    ]
