# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0050_termssettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termssettings',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Page'),
        ),
    ]
