# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 12:43
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0052_auto_20161212_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='lead',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Lead text'),
        ),
        migrations.AlterField(
            model_name='countrypage',
            name='lead',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Lead text'),
        ),
        migrations.AlterField(
            model_name='eventspage',
            name='lead',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Lead text'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='lead',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Lead text'),
        ),
        migrations.AlterField(
            model_name='newsandeventspage',
            name='lead',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Lead text'),
        ),
        migrations.AlterField(
            model_name='projectcountriespage',
            name='lead',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Lead text'),
        ),
        migrations.AlterField(
            model_name='projectcountrypage',
            name='lead',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Lead text'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='lead',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Lead text'),
        ),
        migrations.AlterField(
            model_name='projectsandcountiespage',
            name='lead',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Lead text'),
        ),
        migrations.AlterField(
            model_name='regionpage',
            name='lead',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Lead text'),
        ),
    ]
