# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_auto_20161024_1738'),
        ('cms', '0055_auto_20170405_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='included_countries',
            field=models.ManyToManyField(blank=True, to='countries.Country', verbose_name='Countries without country page'),
        ),
    ]
