# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-25 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexeddocument',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='indexeddocument',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='indexeddocument',
            name='uploaded_by_user',
        ),
        migrations.DeleteModel(
            name='IndexedDocument',
        ),
    ]
